application: palesampleapp
version: 1
runtime: python
api_version: 1

handlers:
# static files html/css/js
- url: (.*)/favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

# admin only stuff
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# scheduled tasks

# dynamic stuff
- url: .*
  script: src/router.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
